// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63cFUV7GhTUMAK_Sn9MotHxCXjP4T2Iw',
    appId: '1:267429879882:web:e136c2d3444602e1ff06b3',
    messagingSenderId: '267429879882',
    projectId: 'tiff-customer-app',
    authDomain: 'tiff-customer-app.firebaseapp.com',
    storageBucket: 'tiff-customer-app.appspot.com',
    measurementId: 'G-CMENTMB1FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp4C1qXYKCgI2bkKTrdcI6ZgiYzfBHQrc',
    appId: '1:267429879882:android:6f807433124f2454ff06b3',
    messagingSenderId: '267429879882',
    projectId: 'tiff-customer-app',
    storageBucket: 'tiff-customer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0VWfyzT9CGzLA8l3q2dXhPjP4ONiFik',
    appId: '1:267429879882:ios:cbe37550fe7b732dff06b3',
    messagingSenderId: '267429879882',
    projectId: 'tiff-customer-app',
    storageBucket: 'tiff-customer-app.appspot.com',
    iosBundleId: 'com.example.tiffinVersion1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0VWfyzT9CGzLA8l3q2dXhPjP4ONiFik',
    appId: '1:267429879882:ios:cbe37550fe7b732dff06b3',
    messagingSenderId: '267429879882',
    projectId: 'tiff-customer-app',
    storageBucket: 'tiff-customer-app.appspot.com',
    iosBundleId: 'com.example.tiffinVersion1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD63cFUV7GhTUMAK_Sn9MotHxCXjP4T2Iw',
    appId: '1:267429879882:web:5d9827f26f12d514ff06b3',
    messagingSenderId: '267429879882',
    projectId: 'tiff-customer-app',
    authDomain: 'tiff-customer-app.firebaseapp.com',
    storageBucket: 'tiff-customer-app.appspot.com',
    measurementId: 'G-XEL37KTP36',
  );
}
